sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull pantuza/vetulus

script:
    - docker run --rm -it --name vetulus pantuza/vetulus bash -c "cd scripts && ./travis_build.sh;"
