language: cpp
compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6 ninja-build
  - cd scripts && sudo ./install_deps.sh

script:
  - pwd && ./travis_build.sh
