sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull pantuza/vetulus
  - zypper install -y python-pyOpenSSL
  - zypper install -y python-pip
  - pip install pip --upgrade
  - pip install PyOpenSSL --upgrade
  - pip install cpp-coveralls
  - docker run --rm -it -p 42500:42500 --name vetulus_stack -d pantuza/vetulus bash -c "cd scripts && ./run_stack_service.sh;"

script:
  - docker run --rm -it --name vetulus pantuza/vetulus bash -c "cd scripts && ./travis_build.sh;"
  - docker exec -it vetulus_stack bash -c "cd scripts && ./test_stack_service.sh;"
after_success:
  - coveralls --gcov-options '\-lp'
