sudo: required

language: cpp

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo pip install pip --upgrade
  - sudo pip install pyOpenSSL --upgrade
  - sudo pip install cpp-coveralls --upgrade
  - docker pull pantuza/vetulus:latest
  - docker run --rm -it -p 42500:42500 --name vetulus_stack -v $(pwd):/vetulus -d pantuza/vetulus:latest bash -c "cd scripts && ./run_stack_service.sh;"

script:
  - docker run --rm -it --name vetulus pantuza/vetulus bash -c "cd scripts && ./travis_build.sh;"
  - docker exec -it vetulus_stack bash -c "cd scripts && ./test_stack_service.sh;"
after_success:
  - coveralls --root services/ --gcov-options '\-lp'
