version: '3'

services:

    vetulus:
        container_name: vetulus
        image: pantuza/vetulus:latest
        ports:
            - "4242:4242"
            - "42500:42500"
        command: sh -c "scripts/compile.sh && scripts/run_docker.sh"
        volumes:
            - .:/vetulus
        networks:
            - net

networks:
    net:
